task_name: "prmbench_bon"
dataset_path: /mnt/petrelfs/songmingyang/code/reasoning/MR_Hallucination/mr_eval/bon_eval/scripts/logs/inference_res_subset50
dataset_type: "dir_of_jsonl"
generation_config:
  max_length: 2048
  temperature: 0
  